Repository opensuspect/opensuspect, pull requests merged in 2020-10, with the labels that each got.

#89 Colorblind mode
  src/assets/common/shaders/colorblind.shader
  src/assets/main/main.gd
  src/assets/main/main.tscn
  src/assets/ui/settings/settings.gd
Labels: accessibility

#117 created FSM and used to to loosen coupling in a few places
  src/assets/autoload/gamemanager.gd
  src/assets/autoload/network.gd
  src/assets/autoload/scenemanager.gd
  src/assets/main/main.gd
  src/assets/main/maps.gd
  src/project.godot
Labels: feature

#150 center settings menu
  src/assets/ui/submenus/settings/settings.gd
  src/assets/ui/submenus/settings/settings.tscn
Labels: bug
